name: Build and Publish Wheel for MeloTTS

on:
  push:
    tags:
      - 'melotts-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clone MeloTTS repository
      run: git clone --depth 1 https://github.com/myshell-ai/MeloTTS.git

    - name: Install Visual C++ Build Tools
      run: |
        choco install visualcpp-build-tools -y

    - name: Install Setup Tools
      run: |
        pip install setuptools wheel

    - name: Install dependencies
      run: |
        pip install torch==2.2.1 --index-url https://download.pytorch.org/whl/cu121
        pip install -r requirements.txt

    - name: Build wheel from installed packages
      run: |
        python setup.py bdist_wheel

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: wheels/*.whl
