name: Build and Publish Wheel for coqui-tts

on:
  push:
    tags:
      - 'chroma-hnswlib-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.13.2]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clone chroma-core hnswlib repository
      run: |
        $commit = "e89eaa84360e17e6f6c27b2a7a9458e0c226fe72";
        git clone --depth 1 https://github.com/chroma-core/hnswlib.git
        cd hnswlib
        git fetch --depth 1 origin $commit
        git checkout $commit

    - name: Install cibuildwheel
      working-directory: hnswlib
      run: python -m pip install cibuildwheel==2.19.1

    - name: Build
      working-directory: hnswlib
      run: |
         python -m cibuildwheel --output-dir dist
      env:
        CIBW_ENVIRONMENT: HNSWLIB_NO_NATIVE=true
        CIBW_ENVIRONMENT_PASS_LINUX: HNSWLIB_NO_NATIVE
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.12"
        CIBW_SKIP: "cp313-win*"
        CIBW_ARCHS_WINDOWS: "AMD64"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: hnswlib/dist/*.whl
