name: Build and Publish Wheel for coqui-tts

on:
  push:
    tags:
      - 'coqui-tts-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11.9]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Visual C++ Build Tools
      run: |
        choco install visualcpp-build-tools -y

    - name: Install Setup Tools
      run: |
        pip install setuptools wheel

    - name: Install coqui-tts
      run: |
        pip install coqui-tts==0.24.1

    - name: Build wheel from installed packages
      run: |
        pip wheel --no-deps --wheel-dir ./wheels coqui-tts

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: wheels/*.whl
