name: Build and Publish Wheel for coqui-tts

on:
  push:
    tags:
      - 'coqui-tts-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11.9]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clone coqui-ai-tts repository
      run: |
        $commit = "e5dd06b3bb15bc777e55fd5f2d1a4a8428fc025a";
        git clone --depth 1 https://github.com/idiap/coqui-ai-TTS.git
        cd coqui-ai-TTS
        git fetch --depth 1 origin $commit
        git checkout $commit

    - name: Install Setup Tools
      working-directory: coqui-ai-TTS
      run: |
        pip install -U pip setuptools wheel build numpy cython

    - name: Build
      working-directory: coqui-ai-TTS
      run: |
        python -m build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: coqui-ai-TTS/dist/*.whl
